# Default values for bk-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: buildkite/agent
  # Note that by default we use appVersion to get image tag version
  # tag:
  pullPolicy: IfNotPresent

# Buildkite Agent settings
agent:
  # Your Buildkite agent token, it must be set
  token: ""
  # Agent tags, which can be used to assign jobs
  tags: "role=agent"

# Enable mounting the hosts docker socket into the agent container
enableHostDocker: true

# Enable security context configuration for the container
securityContext: {}
  # privileged: true

# Enable security context configuration for the pod
podSecurityContext: {}
  # fsGroup: 1000

# Extra env vars to be passed
# If you do want to pass extra env vars to the agent, uncomment the following
# lines, adjust them as necessary.
extraEnv:
#  - name: test1
#    value: "test1"
#  - name: test2
#    value: "test2"

# Mount extra Secrets
# If you do want to mount extra Secrets via volume mounts to the agent container,
# uncomment the following lines, adjust them as necessary.
#
volumeMounts: {}
#  - name: my-secrets
#    value: "/chamber-of-secrets"
#
volumes: {}
#  - name: my-secrets
#    secret:
#      secretName: "some-k8s-secret"

# Your ssh private key if you want to access private git repository
privateSshKey: ""

# Docker registries credentials
registryCreds:
  # GCP credentials for GCR
  # base64 encoded GCP Service account json key file
  gcrServiceAccountKey: ""
  # base64 encoded private registry docker config.json file
  # for quay.io, docker hub, ecr and etc to mount over the container,
  # not to be used with imagePullSecrets
  dockerConfig: ""
  # base64 encoded private registry docker config.json file
  # to be used with imagePullSecrets
  dockerconfigjson: ""

# Add scriptes to /docker-entrypoint.d/ via a ConfigMap
entrypointd: {}
# 01-install-kubectl: |
#   #!/bin/bash
#   set -euo pipefail
#   apt-get update && apt-get install -y kubectl

serviceAccount:
  annotations: {}

 # Uncomment below to enable docker socket liveness probe
livenessProbe:
  # initialDelaySeconds: 15
  # timeoutSeconds: 1
  # exec:
  #   command:
  #   - docker
  #   - ps

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 500m
  #  memory: 1024Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# RBAC manifests management
rbac:
  create: false
  role:
    ## Rules to create. It follows the role specification
    rules:
      - apiGroups:
          - ""
        resources:
          - namespaces
        verbs:
          - watch
          - list
      - apiGroups:
          - ""
        resources:
          - secrets
        verbs:
          - get
          - watch
          - list
      - apiGroups:
          - ""
          - extensions
          - apps
          - batch
        resources:
          - pods
          - replicasets
          - replicationcontrollers
          - statefulsets
          - deployments
          - daemonsets
          - jobs
          - cronjobs
        verbs:
          - get
          - delete
          - watch
          - list
          - update
      - apiGroups:
          - ""
        resources:
          - configmaps
          - secrets
        verbs:
          - get
          - create
          - update

podDisruptionBudget:
  enabled: false
  maxUnavailable: 1
  minAvailable: null

# Extra annotations for the pod
podAnnotations: {}

# Extra "sidecar" containers for the pod
podContainers: {}
# - name: container-name
#   image: container-image:tag
#   args: ["cmd"]
#   env:
#   - name: VAR_NAME
#     value: var_value

# Preconfigured Docker-in-Docker (DinD) container specification
dind:
  enabled: false
  image: docker:19.03-dind
  port: 2375
  resources: {}
  mtu: 1500
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 500m
  #  memory: 1024Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  volumeMounts: {}

# Duration in seconds the pod needs to terminate gracefully.
# May be increased to allow pipelines to complete successfully before the pod is terminated.
terminationGracePeriodSeconds: 30

# Control the lifecycle management for the deployment
lifecycle:
  # if useDefault is true, we will use the buildkite/charts default for managing
  # the lifecycle of the pod. Specifically, we will kill all "buildkite-agent"
  # processes in the container before shutting down. Please note that there is
  # some concern that, on some some container images, this will have the
  # negative effect of causing builds to stop as well. See
  # https://github.com/buildkite/charts/pull/87 for more discussion
  useDefault: true

  # Both preStop and postStart are optional values to be executed for the
  # containers' lifecycle. Note that these cannot be specified if useDefault is
  # true See: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  preStop: {}
  postStart: {}
